package project_Euler;
/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
 * find the sum of the even-valued terms.
 * 
 * @author jonathanasante
 *
 */
public class EvenFibonacciNum {

	public static void main(String[] args) {
		long sum = 2;
		int number = 4;
		
		int []arr = new int[number];
		arr[0] = 1; 
		arr[1] = 2;
		for(int i = 2; arr[i-1] < number; i++){
				arr[i] = arr[i-1] + arr[i - 2];
				if(arr[i] % 2 == 0){
				sum +=arr[i];	
			
				}
					
		}
		
		System.out.println("The sum of the Even valued fibonacci terms less than 4000000 is : " + "\t"+sum);
		
		
		
	}

}
